// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjfRW__veArGVIM5_r6SAP200rFcIO300',
    appId: '1:611998384338:web:cac191a20eba911b712d0b',
    messagingSenderId: '611998384338',
    projectId: 'diet-planner-466fd',
    authDomain: 'diet-planner-466fd.firebaseapp.com',
    storageBucket: 'diet-planner-466fd.appspot.com',
    measurementId: 'G-1BHW05YBKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYS9HGxOeWZ_XGgoYpg3QpwaZRm1XJ3Vk',
    appId: '1:611998384338:android:e561d4f66b7618c3712d0b',
    messagingSenderId: '611998384338',
    projectId: 'diet-planner-466fd',
    storageBucket: 'diet-planner-466fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUo0IfAXHeCJTiLd756yw01YYGP3CDT2I',
    appId: '1:611998384338:ios:8a41461cc6df4cd1712d0b',
    messagingSenderId: '611998384338',
    projectId: 'diet-planner-466fd',
    storageBucket: 'diet-planner-466fd.appspot.com',
    iosBundleId: 'com.example.dietPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUo0IfAXHeCJTiLd756yw01YYGP3CDT2I',
    appId: '1:611998384338:ios:14bc31ce707ba17f712d0b',
    messagingSenderId: '611998384338',
    projectId: 'diet-planner-466fd',
    storageBucket: 'diet-planner-466fd.appspot.com',
    iosBundleId: 'com.example.dietPlanner.RunnerTests',
  );
}
